import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Geist の代わりに Inter をインポート
import "./globals.css";

const inter = Inter({ // Inter フォントを設定
  variable: "--font-inter", // CSS 変数名を変更
  subsets: ["latin"],
});

// geistMono は削除

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`} // Inter の変数を適用 (Mono は削除)
      >
        {children}
      </body>
    </html>
  );
}
